language: c
script:
  - cd src
  - gcc -o hello_c hello.c && ./hello_c
  - g++ -o hello_cpp hello.cpp && ./hello_cpp
  - javac Hello.java && java Hello
  - python hello.py
  - ruby hello.rb
  - perl hello.pl
  - php hello.php
  - go run hello.go
  - rdmd hello.d
  
